name: My First Pipeline

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello! my first CI/CD pipeline is running!"
      - name: Print the current date
        run: date
      - name: List file in the repo
        run: ls -la
